services:
  - type: web
    name: your-django-app
    env: python
    region: oregon  # change if needed
    branch: main    # your main branch
    buildCommand: |
      python3 -m venv env
      source env/bin/activate
      env/bin/pip install --upgrade -r requirements.txt
      env/bin/python3 manage.py migrate
      env/bin/python3 manage.py collectstatic --noinput
    startCommand: env/bin/gunicorn blog_it.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blog_it.settings.production
      - key: DEBUG
        value: 'False'
