# Generated by Django 3.2.1 on 2021-05-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(help_text="Select one or more categories, or <a href='/blog/blog/category/create/'>click here</a> to create a new category.", max_length=32, primary_key=True, serialize=False),
        ),
    ]
