# Generated by Django 3.2.1 on 2021-05-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text="Select zero or more categories, or <a href='/blog/blog/category-create/'>click here</a> to create a new category.", to='blog.BlogCategory'),
        ),
    ]
